### ISSUE TITLE
ES服务启动报错

### ISSUE THREAD

**Issue by asd621457** [ooahz/z2-blog-cloud#1]
Error creating bean with name 'articleController': Injection of resource dependencies failed
![屏幕截图 2024-09-06 215840](https://github.com/user-attachments/assets/7e014632-13a6-41be-88c2-91f10f2298ed)

**Comment by ooahz** [comment]
> Error creating bean with name 'articleController': Injection of resource dependencies failed ![屏幕截图 2024-09-06 215840](https://private-user-images.githubusercontent.com/89506996/365191907-7e014632-13a6-41be-88c2-91f10f2298ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzU0ODMsIm5iZiI6MTcyNTYzNTE4MywicGF0aCI6Ii84OTUwNjk5Ni8zNjUxOTE5MDctN2UwMTQ2MzItMTNhNi00MWJlLTg4YzItOTFmMTBmMjI5OGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE1MDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MThiZjg4MDI4NTA3NzJiMDZkY2VkMjQ4YTdkNzFmOWVmMjcyMTczOTkyNjUzNDEyOTkxMTQ3ODZiNGJlZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SkdHYZD3FWu92SwMcBCVAgFizey-l88ZFO77a0OSO3Q)

初步推测是依赖问题，应该是ArticleRepository类报错了，请检查依赖是否正确下载，search服务所需依赖如下：
![image](https://github.com/user-attachments/assets/2701e2fe-9dfc-4d3e-8896-b2cec19e0a23)

**Comment by asd621457** [comment]
> > Error creating bean with name 'articleController': Injection of resource dependencies failed ![屏幕截图 2024-09-06 215840](https://private-user-images.githubusercontent.com/89506996/365191907-7e014632-13a6-41be-88c2-91f10f2298ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzU0ODMsIm5iZiI6MTcyNTYzNTE4MywicGF0aCI6Ii84OTUwNjk5Ni8zNjUxOTE5MDctN2UwMTQ2MzItMTNhNi00MWJlLTg4YzItOTFmMTBmMjI5OGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE1MDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MThiZjg4MDI4NTA3NzJiMDZkY2VkMjQ4YTdkNzFmOWVmMjcyMTczOTkyNjUzNDEyOTkxMTQ3ODZiNGJlZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SkdHYZD3FWu92SwMcBCVAgFizey-l88ZFO77a0OSO3Q)
> 
> 初步推测是依赖问题，应该是ArticleRepository类报错了，请检查依赖是否正确下载，search服务所需依赖如下： ![image](https://private-user-images.githubusercontent.com/57132258/365215246-2701e2fe-9dfc-4d3e-8896-b2cec19e0a23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Mzg1MjQsIm5iZiI6MTcyNTYzODIyNCwicGF0aCI6Ii81NzEzMjI1OC8zNjUyMTUyNDYtMjcwMWUyZmUtOWRmYy00ZDNlLTg4OTYtYjJjZWMxOWUwYTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE1NTcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ODUxOTAzOWI5N2E3ZTE2MzNiOWUyNTljODczMDY3OTMzMzlmZTYxMzUyOTljMmExNjk3MGRhY2QzODY2MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.apo4fU7rIwSbzr_8gRqKfCgP0wDnZmz3a0LnSUxA_14)

依赖正确下载，报错无法解决

**Comment by asd621457** [comment]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'articleController': Unsatisfied dependency expressed through field 'articleService': Error creating bean with name 'articleServiceImpl': Unsatisfied dependency expressed through field 'articleRepository': Error creating bean with name 'articleRepository' defined in cn.ahzoo.search.repository.ArticleRepository defined in @EnableElasticsearchRepositories declared on SearchApplication: Failed to instantiate [org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository]: Constructor threw exception
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:787)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:767)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:508)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1419)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:959)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at cn.ahzoo.search.SearchApplication.main(SearchApplication.java:20)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'articleServiceImpl': Unsatisfied dependency expressed through field 'articleRepository': Error creating bean with name 'articleRepository' defined in cn.ahzoo.search.repository.ArticleRepository defined in @EnableElasticsearchRepositories declared on SearchApplication: Failed to instantiate [org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository]: Constructor threw exception
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:787)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:767)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:508)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1419)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:784)
	... 20 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'articleRepository' defined in cn.ahzoo.search.repository.ArticleRepository defined in @EnableElasticsearchRepositories declared on SearchApplication: Failed to instantiate [org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository]: Constructor threw exception
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:784)
	... 34 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository]: Constructor threw exception
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:223)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.lambda$instantiateClass$5(RepositoryFactorySupport.java:571)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.instantiateClass(RepositoryFactorySupport.java:571)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getTargetRepositoryViaReflection(RepositoryFactorySupport.java:536)
	at org.springframework.data.elasticsearch.repository.support.ElasticsearchRepositoryFactory.getTargetRepository(ElasticsearchRepositoryFactory.java:79)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:317)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:279)
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:135)
	at org.springframework.data.util.Lazy.get(Lazy.java:113)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:285)
	at org.springframework.data.elasticsearch.repository.support.ElasticsearchRepositoryFactoryBean.afterPropertiesSet(ElasticsearchRepositoryFactoryBean.java:69)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1833)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	... 44 common frames omitted
Caused by: co.elastic.clients.json.JsonpMappingException: Error deserializing co.elastic.clients.elasticsearch._types.mapping.KeywordProperty: Unknown field 'analyzer' (JSON path: properties.title.analyzer) (in object at line no=1, column no=114, offset=113)
	at co.elastic.clients.json.ObjectDeserializer.parseUnknownField(ObjectDeserializer.java:233)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:190)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:148)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:77)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:78)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:209)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:148)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:77)
	at co.elastic.clients.json.BuildFunctionDeserializer.deserialize(BuildFunctionDeserializer.java:47)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
	at co.elastic.clients.json.JsonpDeserializerBase$StringMapDeserializer.deserialize(JsonpDeserializerBase.java:349)
	at co.elastic.clients.json.JsonpDeserializerBase$StringMapDeserializer.deserialize(JsonpDeserializerBase.java:333)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:77)
	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:78)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:192)
	at co.elastic.clients.util.WithJsonObjectBuilderBase.withJson(WithJsonObjectBuilderBase.java:54)
	at co.elastic.clients.json.WithJson.withJson(WithJson.java:57)
	at org.springframework.data.elasticsearch.client.elc.TypeUtils.lambda$typeMapping$3(TypeUtils.java:470)
	at co.elastic.clients.elasticsearch._types.mapping.TypeMapping.of(TypeMapping.java:122)
	at org.springframework.data.elasticsearch.client.elc.TypeUtils.typeMapping(TypeUtils.java:470)
	at org.springframework.data.elasticsearch.client.elc.RequestConverter.indicesCreateRequest(RequestConverter.java:245)
	at org.springframework.data.elasticsearch.client.elc.IndicesTemplate.doCreate(IndicesTemplate.java:144)
	at org.springframework.data.elasticsearch.client.elc.IndicesTemplate.createWithMapping(IndicesTemplate.java:135)
	at org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository.<init>(SimpleElasticsearchRepository.java:86)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:210)
	... 57 common frames omitted

**Comment by ooahz** [comment]
可以从以下情况排查：
在es已经启动并且访问地址为`localhost:9200`的前提下：

1. es的版本为8.0以上，且启动时使用的jdk21；
2. 本地浏览器访问`http://localhost:9200`可以看到es的启动成功的相关信息（注意是**http://**，而不是**https://**）；
3. 本地浏览器访问`http://localhost:9200`不需要输入密码；
4. 本项目的默认es配置是没有配置ssl和密码的，而es8+版本默认是配置ssl的。请确认你已关闭es的ssl和密码，否则请自行针对此进行额外的配置

**Comment by asd621457** [comment]
> 可以从以下情况排查： 在es已经启动并且访问地址为`localhost:9200`的前提下：
> 
> 1. es的版本为8.0以上，且启动时使用的jdk21；
> 2. 本地浏览器访问`http://localhost:9200`可以看到es的启动成功的相关信息（注意是**http://**，而不是**https://**）；
> 3. 本地浏览器访问`http://localhost:9200`不需要输入密码；
> 4. 本项目的默认es配置是没有配置ssl和密码的，而es8+版本默认是配置ssl的。请确认你已关闭es的ssl和密码，否则请自行针对此进行额外的配置

![屏幕截图 2024-09-07 105044](https://github.com/user-attachments/assets/793c73d9-cc9e-4c92-b6ec-2c958188dd6d)
![屏幕截图 2024-09-07 105055](https://github.com/user-attachments/assets/34ff70da-25ad-4e10-b5fd-9f6e7b5ddf48)
已完成排查，均符合相关配置要求

**Comment by ooahz** [comment]
> > 可以从以下情况排查： 在es已经启动并且访问地址为`localhost:9200`的前提下：
> > 
> > 1. es的版本为8.0以上，且启动时使用的jdk21；
> > 2. 本地浏览器访问`http://localhost:9200`可以看到es的启动成功的相关信息（注意是**http://**，而不是**https://**）；
> > 3. 本地浏览器访问`http://localhost:9200`不需要输入密码；
> > 4. 本项目的默认es配置是没有配置ssl和密码的，而es8+版本默认是配置ssl的。请确认你已关闭es的ssl和密码，否则请自行针对此进行额外的配置
> 
> ![屏幕截图 2024-09-07 105044](https://private-user-images.githubusercontent.com/89506996/365335935-793c73d9-cc9e-4c92-b6ec-2c958188dd6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Nzk3ODMsIm5iZiI6MTcyNTY3OTQ4MywicGF0aCI6Ii84OTUwNjk5Ni8zNjUzMzU5MzUtNzkzYzczZDktY2M5ZS00YzkyLWI2ZWMtMmM5NTgxODhkZDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAzMjQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMjdjZWUxMjIxOWM0NThmMDUxYjcyMWY0ZDE5YWI0ODljZWM3ZjRjMTBhODU0YzhjYzc0YmU4ZDE3YWQ0NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mMcNqxiXD6tdIPxCX-kae7UOQjut6x5QD9jIxXdgN3I) ![屏幕截图 2024-09-07 105055](https://private-user-images.githubusercontent.com/89506996/365335942-34ff70da-25ad-4e10-b5fd-9f6e7b5ddf48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Nzk3ODMsIm5iZiI6MTcyNTY3OTQ4MywicGF0aCI6Ii84OTUwNjk5Ni8zNjUzMzU5NDItMzRmZjcwZGEtMjVhZC00ZTEwLWI1ZmQtOWY2ZTdiNWRkZjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAzMjQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZGI3NzJjMWY3OTUzMmM2NTg0ZjYyMTgxOTAxNjA1NDk0ZTQ1ODhhOTVhYWE4ZWM2MWRlN2IwMmI4MmFlOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OpjTHpGaXK2_Mu6oCBzJtcRGH-_wyiPcAnik8SCmtR4) 已完成排查，均符合相关配置要求

我这边给你提供个es的临时远程访问地址（将在1小时内关闭），你将 `elasticsearch.uris`配置为：`es.ouo.pub` 尝试能否启动

**Comment by asd621457** [comment]
> > > 可以从以下情况排查： 在es已经启动并且访问地址为`localhost:9200`的前提下：
> > > 
> > > 1. es的版本为8.0以上，且启动时使用的jdk21；
> > > 2. 本地浏览器访问`http://localhost:9200`可以看到es的启动成功的相关信息（注意是**http://**，而不是**https://**）；
> > > 3. 本地浏览器访问`http://localhost:9200`不需要输入密码；
> > > 4. 本项目的默认es配置是没有配置ssl和密码的，而es8+版本默认是配置ssl的。请确认你已关闭es的ssl和密码，否则请自行针对此进行额外的配置
> > 
> > 
> > ![屏幕截图 2024-09-07 105044](https://private-user-images.githubusercontent.com/89506996/365335935-793c73d9-cc9e-4c92-b6ec-2c958188dd6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Nzk3ODMsIm5iZiI6MTcyNTY3OTQ4MywicGF0aCI6Ii84OTUwNjk5Ni8zNjUzMzU5MzUtNzkzYzczZDktY2M5ZS00YzkyLWI2ZWMtMmM5NTgxODhkZDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAzMjQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMjdjZWUxMjIxOWM0NThmMDUxYjcyMWY0ZDE5YWI0ODljZWM3ZjRjMTBhODU0YzhjYzc0YmU4ZDE3YWQ0NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mMcNqxiXD6tdIPxCX-kae7UOQjut6x5QD9jIxXdgN3I) ![屏幕截图 2024-09-07 105055](https://private-user-images.githubusercontent.com/89506996/365335942-34ff70da-25ad-4e10-b5fd-9f6e7b5ddf48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Nzk3ODMsIm5iZiI6MTcyNTY3OTQ4MywicGF0aCI6Ii84OTUwNjk5Ni8zNjUzMzU5NDItMzRmZjcwZGEtMjVhZC00ZTEwLWI1ZmQtOWY2ZTdiNWRkZjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAzMjQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZGI3NzJjMWY3OTUzMmM2NTg0ZjYyMTgxOTAxNjA1NDk0ZTQ1ODhhOTVhYWE4ZWM2MWRlN2IwMmI4MmFlOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OpjTHpGaXK2_Mu6oCBzJtcRGH-_wyiPcAnik8SCmtR4) 已完成排查，均符合相关配置要求
> 
> 我这边给你提供个es的临时远程访问地址（将在1小时内关闭），你将 `elasticsearch.uris`配置为：`es.ouo.pub` 尝试能否启动

我的es版本过高吗？博主提供的es可以正常启动

**Comment by ooahz** [comment]
> 
> 我的es版本过高吗？博主提供的es可以正常启动

不，我这边使用的es版本是8.13.4，实际比你的版本要高的。既然已经确定是es客户端的问题，剩下的问题还请自行排查
